// layout.js
import { Inter } from "next/font/google";
import "./globals.css";
import { Amplify } from 'aws-amplify';
import awsmobile from '../../aws-exports';
import React from "react";

const inter = Inter({ subsets: ["latin"] });

// 配置 AWS Amplify
Amplify.configure(awsmobile);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
